// This file is generated by FlutterFire CLI.
// Run: flutterfire configure --project=jedi-security-core
// to regenerate this file for your environment.
//
// ──────────────────────────────────────────────────────────────────────────
// IMPORTANT: Replace the placeholder values below with the real values from
// your Firebase console (Project settings → Your apps → SDK setup).
//
// Steps:
//   1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//   2. Run:  flutterfire configure --project=jedi-security-core
//   3. This file will be auto-generated with the correct values.
// ──────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE THESE VALUES WITH YOUR REAL FIREBASE CONFIG ─────────────────
  // Obtain them from: Firebase Console → Project Settings → Your apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'YOUR_WEB_API_KEY',
    appId:             'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'jedi-security-core',
    authDomain:        'jedi-security-core.firebaseapp.com',
    storageBucket:     'jedi-security-core.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'YOUR_ANDROID_API_KEY',
    appId:             'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'jedi-security-core',
    storageBucket:     'jedi-security-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'YOUR_IOS_API_KEY',
    appId:             'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'jedi-security-core',
    storageBucket:     'jedi-security-core.firebasestorage.app',
    iosBundleId:       'com.example.jedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:            'YOUR_MACOS_API_KEY',
    appId:             'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'jedi-security-core',
    storageBucket:     'jedi-security-core.firebasestorage.app',
    iosBundleId:       'com.example.jedi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:            'YOUR_WINDOWS_API_KEY',
    appId:             'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'jedi-security-core',
    storageBucket:     'jedi-security-core.firebasestorage.app',
  );
}
